### ISSUE TITLE
Error on running in windows 10

### ISSUE THREAD

**Issue by JakeWrights** [BenjaminVanRyseghem/next-action-clojure#4]
Hmm getting this error when running the program

http://puu.sh/uS1Dn/69fee0afa0.png

Any thoughts?

Thanks!!

**Comment by BenjaminVanRyseghem** [comment]
can you copy/paste the command you use to run the program please?

(TBH I haven't touch this code in years so :smile: )

**Comment by JakeWrights** [comment]
Sure.
I just in the command line put in 
java next-action-1.0.0-standalone.jar

**Comment by BenjaminVanRyseghem** [comment]
that's the problem

By default java expect a class name, not a jar file

the command should be

```
java -jar next-action-1.0.0-standalone.jar
```

BTW, it was written in the README 😛

**Comment by JakeWrights** [comment]
I see, thanks a lot!
